name: "Code quality"
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Linter
        uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          npmInstall: false

      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
